- controllers/suite_test.go
- go.mod
- go.sum
Run the go mod tidy command so the check for it passes
Clean up the syntax errors caught in `controllers/suite_test.go`
> Run go mod tidy and fix syntax error in suite_test.go

- controllers/release_controller.go
Adds new conditions to two new cases:
* ReleaseLink not found
* ReleaseStrategy not found
> Add more status on error

- api/v1alpha1/release_types.go
- config/crd/bases/appstudio.redhat.com_releases.yaml
- controllers/pipelinerun_controller.go
- controllers/release_controller.go
This is meant only for the M4 demo and should be properly reviewed after it.
> Fix Error status

- demos/m4/README.md
- demos/m4/failures/missing_matching_release_link.yaml
- demos/m4/failures/missing_release_pipeline.yaml
- demos/m4/failures/missing_release_strategy.yaml
- demos/m4/failures/release_link_targets_own_workspace.yaml
> Add some demo failure scenarios

- .github/workflows/pr.yml
- .gitlint
Add conventional-commit checking that will be run on commit messages
that are added in new pull requests. Run the check as part of pr github
action.
> feat(HACBS-402): add conventional-commit checks

- api/v1alpha1/releasestrategy_types.go
- config/crd/bases/appstudio.redhat.com_releasestrategies.yaml
The comment for this field was incorrect.
> fix: fix ServiceAccount field comment

- controllers/release/release_adapter.go
- tekton/pipeline_run.go
This reverts commit 31f250f3e1e09916c8def8a570768b497817d01b.
> revert: pass release to the Release pipeline

- api/v1alpha1/release_types.go
- api/v1alpha1/release_webhook.go
- api/v1alpha1/releaselink_webhook.go
- api/v1alpha1/releasestrategy_types.go
- config/crd/bases/appstudio.redhat.com_releasestrategies.yaml
- controllers/release/release_adapter.go
- tekton/pipeline_run.go
General clean-up to ensure code quality in the repo before start addressing M6 goals.
> refactor: clean-up release-service code

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
As part of this PR I'm updating the README.md and adding new CONTRIBUTE.md and CODE_OF_CONDUCTS.md files. These files are needed so people engaging with the repository know how to contribute and collaborate with other users.
> docs: update repository documents

- tekton/pipeline_run_test.go
- tekton/tekton_suite_test.go
This commit adds the first set of Unit Tests for `PipelineRun`s
short note: This is a work in progress - just adding the PR for earlier review as it is 1st one.
> test(HACBS-668): add the first set of Unit Tests for `PipelineRun`s

- tekton/pipeline_run_test.go
- tekton/predicates_test.go
- tekton/tekton_suite_test.go
- tekton/utils_test.go
- adds UnitTests for tekton directory
> test(HACBS-726): add unit tests to tekton functions in tekton

- controllers/release/release_adapter.go
Although it hasn't being a problem until now, with the addition of tests we have started to see problems raised by the update of resources. This could be solved by fixing the tests, but it's a good moment to move to using Patch as it was suggested by Brian Cook.
> feat(HACBS-965): use Patch instead of Update

- controllers/release/release_adapter_test.go
- controllers/release/release_controller_test.go
- controllers/release/release_suite_test.go
- go.mod
- go.sum
adds release_controller tests
adds release_adapter tests
bumps up ginkgo to v2
> test(HACBS-774): increase coverage in controllers/release/ directory

- controllers/results/operation_results_test.go
- adds test to `results/` directory
> test(HACBS-913): increase coverage in controllers/results/ directory

- codecov.yml
> chore: changes codecov settings

- CONTRIBUTING.md
- adds testing section in CONTRIBUTING.md
- adds advices and links in testing section
> docs: adding testing section in CONTRIBUTING.md

- .github/workflows/pr.yml
> chore: update codecov version to v3

- metrics/release_suite_test.go
- metrics/release_test.go
- adds tests for `metrics/` directory
> test(HACBS-798): increase test coverage on metrics/ directory

- controllers/release/release_adapter_test.go
Fixes flaky release_adapter tests
- moves releasePlan/releaseAdmissionPlan creation to BeforeAll Block
- moves the test of unexistent releasePlan to the bottom
> fix(HACBS-1126): test suite for controllers/release is flaky

- config/kcp/kustomization.yaml
> fix: wrong filenames in kcp dir

- controllers/release/release_adapter.go
- controllers/release/release_adapter_test.go
- gitops/binding_test.go
- gitops/gitops_suite_test.go
- syncer/syncer_suite_test.go
- syncer/syncer_test.go
When the new functionally was added for M7 demo, tests were not ready. This commit adds tests for all the new functions and files.
Depends on #101 
> test(HACBS-1095): add tests for GitOps functionality

- controllers/release/release_adapter_test.go
> fix: restore releasePlan workspace in test modifying it

- test/paths_test.go
This commit replaces Should with To to improve the reading.
> chore: use proper GomegaMatchers

- controllers/release/cache.go
> fix: nit pick incorrect function names

- Makefile
> feat: add make target for creating local certs

- api/v1alpha1/release_types_test.go
- api/v1alpha1/release_webhook_test.go
- api/v1alpha1/releaseplan_webhook_test.go
- api/v1alpha1/releaseplanadmission_webhook_test.go
api tests
* Improve test coverage in api/v1alpha1 directory.
> feat(hacbs-773): add unit tests for api directory

- Dockerfile
- controllers/release/release_adapter.go
- go.mod
- metadata/metadata.go
- metadata/metadata_test.go
- tekton/pipeline_run.go
- tekton/pipeline_run_test.go
- tekton/predicates_test.go
- tekton/tekton_suite_test.go
- tekton/utils_test.go
> feat(hacbs-1193): copy pac metadata to pipelinerun

- api/v1alpha1/groupversion_info.go
- controllers/release/release_adapter_test.go
- controllers/release/release_suite_test.go
- go.mod
- go.sum
- tekton/pipeline_run_test.go
We were using an old version of the EC resources and the current dependency was causing problems
> fix: replace ec dependency and fix tests

- .tekton/pull-request.yaml
- .tekton/push.yaml
volumeClaimTemplate provides PVC cleanup out-of-box.
> feat: use volumeClaimTemplate instead of static PVC

- metrics/release.go
> docs: add license header

- .github/workflows/pr.yml
We had some deprecation warnings so I'm bumping the version.
> feat: update cache action version

- config/rbac/internal_service_request_role.yaml
- config/rbac/internal_service_request_role_binding.yaml
- config/rbac/internal_service_request_service_account.yaml
> feat(hacbs-1432): signing service account

- config/manager/kustomization.yaml
- config/manager/network_policy.yaml
Applied PR as per https://issues.redhat.com/browse/HACBS-1308 - Put a network policy around release-service controller, prevent egress to everywhere
> feat(HACBS-1308) : add a deny all network policy

- gitops/utils.go
- gitops/utils_test.go
> feat(HACBS-1645): watch binding status going from false to true

- api/v1alpha1/releaseplanadmission_types.go
- config/crd/bases/appstudio.redhat.com_releaseplanadmissions.yaml
> fix(HACBS-1699): releaseStrategy not showing in get of RPA

- controllers/release/release_adapter.go
- controllers/release/release_adapter_test.go
If there are two ReleasePlanAdmissions in the managed namespace with the same origin, but different applications, the one with the matching application should be returned, not just index 0 of the list of ReleasePlanAdmissions found in the managed namespace that have a matching origin.
> fix: return ReleasePlanAdmission with matching application

- .tekton/push.yaml
- See redhat-appstudio/infra-deployments#1273
Signed-off-by: Scott Hebert <shebert@redhat.com>
> fix(HACBS-1606): fix script that updates dashboard

- controllers/release/release_adapter.go
- controllers/release/release_adapter_test.go
When the release service processes multiple snapshots for the same application and environment, it should create one binding and then update it for each successive snapshot. This commit changes the behavior from creating a new binding each time to the desired behavior.
> feat(HACBS-1747): update binding if one already exists

- tekton/pipeline_run.go
In this house we follow the rules of ABC!
> chore: fix ordering

- .tekton/push.yaml
This line was already present but had to be removed to apply other changes. This commit simply put it back in.
> feat: update grafana reference on push

- config/grafana/dashboards/release_dashboard.json
This commit adds a new panel and fix some bugs on the release dashboard.
> feat: improve release dashboard

- api/v1alpha1/author_webhook_test.go
- api/v1alpha1/release_types_test.go
- api/v1alpha1/release_webhook_test.go
- api/v1alpha1/releaseplan_webhook_test.go
- api/v1alpha1/releaseplanadmission_webhook_test.go
- conditions/conditions_test.go
- controllers/release/adapter_test.go
- controllers/release/controller_test.go
- gitops/binding_test.go
- gitops/predicates_test.go
- gitops/utils_test.go
- loader/loader_mock_test.go
- loader/loader_test.go
- metrics/release_test.go
- tekton/pipeline_run_test.go
- tekton/predicates_test.go
- tekton/utils_test.go
This change is done to align with E2E tests.
> refactor: replace Context with When

- .tekton/pull-request.yaml
- .tekton/push.yaml
- Testing workaround that specifies kind=Pipeline for PipelineRuns
> chore(ci): add workaround for new osp ver

- controllers/release/adapter.go
- controllers/release/adapter_test.go
The EnsureReleaseIsValid operation uses nested patches. This leads to some unexpected behavior. This commit breaks the operation into multiple validation operations to work around the bug.
> fix(HACBS-2549): operation EnsureReleaseIsValid is buggy

- tekton/utils/pipeline_ref.go
- tekton/utils/pipeline_ref_test.go
- tekton/utils/suite_test.go
This will be used for enabling git resolvers in release strategy CR.
> feat(HACBS-2461): add new pipeline_ref type 

- go.mod
- go.sum
This commit updates the EC dependency to use the latest code.
> feat: use latest EC API 

- .tekton/release-service-pull-request.yaml
- .tekton/release-service-push.yaml
> chore: enable source builds

- go.mod
- go.sum
> chore: bump tektoncd go mod version

- controllers/release/adapter.go
This commit improves the error checking when creating a RoleBinding for the managed pipelineRun.
> fix(RHTAPREL-371): add error checking when creating RoleBinding

- .github/dependabot.yml
chore: removing Troy and Kasem from dependabot
> chore: removing Troy and Kasem from dependabot

- config/grafana/saas-dashboards/release_service_breakdown.yaml
This commit adds an extra dashboard with more information about the release service.
> feat(RELEASE-1031): new breakdown dashboard

- integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
> fix: don't run e2e tests on bot PRs

- .tekton/release-service-pull-request.yaml
- .tekton/release-service-push.yaml
Starting from 1st of April 2025, the Shell Check (sast-shell-check) and Unicode (sast-unicode-check)
will become required tasks
> chore: add required sast checks to pipelineRuns

- config/rbac/role.yaml
- controllers/release/controller.go
- need ability to create roles and access secrets
> feat(RELEASE-1464): update controller rbac

- go.mod
- go.sum
This is to address CVE-2025-22868.
> fix(RELEASE-1763): update oauth2 module

- .github/workflows/pr-assigner.yaml
This commit adds a new workflow to automate PR assigments.
> feat(RELEASE-1764): automate pr assigments
