.github/workflows/pr.yml
This saves us time as we don't need to install rpms
into the fedora container every time
Also application-service runs on ubuntu since it is native to github actions
=> Use native ubuntu container for github pr tests

.github/workflows/push.yml, Makefile
Whenever a new commit is pushed to the main branch
of the repo, the bundle will be built and the result
will be pushed to quay.io/redhat-appstudio/release-service
=> Add GitHub action to push image to Quay

.github/workflows/pr.yml
Add checks to our per PR CI that ensures both the
make build and make bundle targets run successfully
=> Add checks for make build and bundle

controllers/release_controller.go, go.mod
Add validations to the release controller to check that the
ReleaseLink referenced in the Release both targets an existing
workspace and that there is a corresponding ReleaseLink in the
target workspace pointing back to the ReleaseLink. If either is
untrue, error out.
=> Add ReleaseLink validation to release controller

demos/m4/README.md, demos/m4/base/kustomization.yaml, demos/m4/base/namespaces.yaml, demos/m4/base/release_links.yaml, demos/m4/base/release_strategy.yaml, demos/m4/overlays/dev/component.yaml, demos/m4/overlays/dev/kustomization.yaml, demos/m4/overlays/dev/pipeline_run.yaml, demos/m4/overlays/dev/tekton_feature_flags_config_map.yaml, demos/m4/overlays/staging/application.yaml, demos/m4/overlays/staging/component.yaml, demos/m4/overlays/staging/kustomization.yaml
This PR adds resources and information for M4 demo. It uses kustomize to be able to run it in a dev environment (with CRC and Openshift Pipelines) and in staging (with a cluster bootstrapped with infra-deployments).
=> Add instructions for M4 demo

controllers/release_controller.go, demos/m4/base/release_links.yaml, demos/m4/base/release_strategy.yaml, demos/m4/overlays/dev/pipeline_run.yaml
We were fetching the strategy name from the ReleaseLink in the user's workspace, which doesn't have that value. This commit fix the issue, loading the remote ReleaseLink and getting the strategy from that resource.
=> Get strategy from the right ReleaseLink

PROJECT, api/v1alpha1/release_webhook.go, api/v1alpha1/webhook_suite_test.go, config/webhook/manifests.yaml, main.go
The new webhook will forbid updates to Releases as these resources should not be updated once created. At that point the controller is already processing them and adding data specific to the fields in the resource specification.
=> Add release webhook

.tekton/pull-request.yaml, .tekton/push.yaml
This will enable release-service repo to easily configure Tekton as CI for PR checks.
The goal of Pipelines as Code is to let you define your Tekton templates inside your source code repository and have the pipeline run and report the status of the execution when triggered by a Pull Request or a Push.
related PR on infra-deployments: https://github.com/redhat-appstudio/infra-deployments/pull/283
=> setup Pipelines-as-Code for release-service

config/crd/kustomization.yaml, config/default/kustomization.yaml, config/default/webhookcainjection_patch.yaml, config/webhook/service.yaml
This change follows what application-service did for enabling webhooks on staging [1]. With this change, webhooks will not work on CRC.
[1] https://github.com/redhat-appstudio/application-service/pull/52
=> Remove cert-manager

.tekton/push.yaml
This PR deletes the infra-deployments-deploy-key secret, as there is a sharedSecret created for all the namespaces, there is no need for an individual secret to be added to each namespace.
Signed-off-by: Bharat Kumar Mallavarapu mbharatk@redhat.com
=> fix: remove deploy-key secret

tekton/pipeline_run.go
As reported by John Bieren, the current implementation of WithReleaseStrategy overrides the Pipeline Spec, which should not be the case. This would force us to run WithReleaseStrategy before WithExtraParams so it doesn't override them.
=> fix(HACBS-508): do not override Pipeline spec

api/v1alpha1/release_webhook.go, api/v1alpha1/release_webhook_test.go, api/v1alpha1/release_webhook_unit_test.go
The Release admission webhook was preventing the objects to be updated to add a finalizer. The admission webhook for updates should exclusively prevent spec updates.
=> fix(HACBS-509): prevent spec updates exclusively

demos/m5/README.md, demos/m5/base/application_snapshot.yaml, demos/m5/base/kustomization.yaml, demos/m5/base/namespaces.yaml, demos/m5/base/release_links.yaml, demos/m5/base/release_strategy.yaml, demos/m5/base/tekton_feature_flags_config_map.yaml, demos/m5/overlays/dev/kustomization.yaml, demos/m5/overlays/dev/release.yaml, demos/m5/overlays/staging/kustomization.yaml
Adds new demo files to trigger the operator through the creations of a Release. Component and Application references have been removed.
=> feat(HACBS-471): add demo files for M5

Makefile
The operator Makefile was outdated for recent Go versions. Specifically, the routine to install Go binaries was deprecated and should be using `go install` instead of `go get`.
=> fix(HACBS-513): use go install to fetch binaries

controllers/release/release_adapter.go, tekton/pipeline_run.go
Extract the ApplicationSnapshot from the Release CR that is being processed
and pass that as a parameter to the Release pipeline.
=> feat(HACBS-392): pass ApplicationSnapshot to Release pipeline

tekton/pipeline_run.go
This commit adds the functionality to pass the policy defined in
the release strategy to the release pipeline run so that the
Enterprise Contract task can access it.
=> feat(HACBS-551): pass Policy to release PipelineRun

api/v1alpha1/applicationsnapshot_types.go, config/crd/bases/appstudio.redhat.com_applicationsnapshots.yaml
This commit adds the additional 'application' spec field to
the ApplicationSnapshot CRD.
Signed-off-by: Krunoslav Pavic <kpavic@redhat.com>
=> feat(HACBS-514): add application spec field to ApplicationSnapshot

config/rbac/applicationsnapshot_role_binding.yaml, config/rbac/kustomization.yaml, config/rbac/role.yaml, controllers/release/release_controller.go
We are currently seeing failures when accessing ApplicationSnapshots. This is due to the fact that don't have set proper RBAC for that resource. This commit adds the proper permissions.
=> feat(HACBS-572): add rbac for ApplicationSnapshots

demos/m5/overlays/dev/release.yaml
The name of the ReleaseLink in the Release was incorrect.
=> fix(HACBS-571): use proper ReleaseLink name

demos/m5/base/application_snapshot.yaml
With the recent changes in the ApplicationSnapshot CRD, we are now missing the Application name.
=> fix(HACBS-596): add missing Application name

.github/gitlint/contrib_description_conventional_commits.py, .gitlint
We are following Conventional Commits and using Gitlint to enforce the specification. Although the description doesn't have a set-on-stone format, examples on Conventional Commits spec seem to use always a sentence starting with lowercase. This is not enforced by Gitlint, but I think it would be good to enforce it. First because all our commits will follow the same convention. Second because a new user following the spec will already think this is the proper way.
=> fix(HACBS-510): fail on description starting with uppercase

api/v1alpha1/releasestrategy_types.go, config/crd/bases/appstudio.redhat.com_releasestrategies.yaml, tekton/pipeline_run.go
This commit allows to specify a service account for the release PipelineRun. We are going to need to pass a service account to be able to clone private repositories (at least).
=> feat(HACBS-541): add serviceAccount field

tekton/pipeline_run.go
The parameter name for the snapshot was ApplicationSnapshot, when it should be applicationSnapshot.
=> fix(HACBS-605): use camel case for snapshot parameter

controllers/release/release_adapter.go, tekton/pipeline_run.go
The Release pipeline will make use of a workspace. To make sure nothing gets overwritten while running multiple pipelines, we need to use a subpath. For this, we can make use of the release name in the format `<namespace>/<name>`.
=> feat(HACBS-606): pass release to the Release pipeline

api/v1alpha1/releaselink_webhook.go, config/webhook/manifests.yaml
This commit adds a mutating webhook for ReleaseLink CRs. The webhook
checks to see if the release.appstudio.openshift.io/auto-release label
exists. If it does not exist, it adds it with a value of true. If it
does exist (meaning the user added the label when creating the CR),
it will do nothing.
=> feat(HACBS-555): add auto-release label to ReleaseLinks

api/v1alpha1/releaselink_webhook.go, api/v1alpha1/releaselink_webhook_test.go, api/v1alpha1/releaselink_webhook_unit_test.go
The release.appstudio.openshift.io/auto-release label for ReleaseLinks can be
manually set or edited once the ReleaseLink is created. This commit forces updates
to the label to only set the value to true or false.
=> feat(HACBS-681): force ReleaseLink auto-release to be only true or false

Dockerfile, README.md, api/v1alpha1/release_types.go, config/crd/bases/appstudio.redhat.com_releases.yaml, config/default/kustomization.yaml, config/manager/manager.yaml, config/rbac/kustomization.yaml, config/rbac/prometheus_role_binding.yaml, config/rbac/prometheus_viewer_role.yaml, controllers/release/release_adapter.go, go.mod, metrics/release.go
This commit adds metrics to the release resource so we can support the Release Service SLIs. In addition, adds changes to allow the Prometheus instance in openshift-monitoring to scrap our ServiceMonitor.
=> feat(HACBS-154): add release metrics

.github/codecov.yml, .github/workflows/pr.yml, codecov.yml
This change configures the CI to push coverage reports to Codecov whenever a PR to main is created or there is a push to the main branch.
A codecov.yml file has been added to ignore those files that should not be part of the report.
=> feat(HACBS-776): submit coverage reports to codecov

api/v1alpha1/release_types.go, metrics/release.go
This commit changes the release_attempt_duration_seconds and release_attempt_total metrics to add labels registering the reason, strategy, target workspace and whether the release succeeded or not.
In addition, the release_attempt_total is now registered once the release is completed and not when it's first seen.
=> feat(HACBS-782): register more labels

.github/workflows/pr.yml, Makefile, config/kcp/apiexport_release.yaml, config/kcp/apiresourceschema_release.yaml, config/kcp/kustomization.yaml, hack/generate-kcp-api.sh
This commit adds the APIResourceSchema for the release service. This
is needed for KCP integration. The generate-kcp-api.sh script is copied
from the has and spi repos.
=> feat(HACBS-694): generate APIResourceSchema

api/v1alpha1/release_types.go
HasSucceeded function was returned the opposite value of what it should return.
Thanks to @dirgim for noticing and reporting this bug.
=> fix(HACBS-858): fix HasSucceeded to return a valid value

controllers/release/release_adapter_test.go
The default timeout (1s) is not enough and was causing problems.
=> fix: add timeout to every Eventually block

controllers/release/release_adapter_test.go
Just a minor change to remove redundant parenthesis.
=> fix: remove redundant parenthesis

controllers/release/release_adapter.go, controllers/release/release_adapter_test.go
There was an edge case in which the finalization could fail when the PipelineRun was not present.
=> fix(HACBS-987): fix finalization when no PR is present

.github/workflows/pr.yml
Checkout the v0.7.1 branch, which is currently kcp-stable, in
our github action workflow before running the make targets.
=> fix: checkout kcp branch in ci

Dockerfile
The current image was causing problems while building the operator as buildah doesn't use Docker Hub by default.
=> fix(HACBS-1027): use a Red Hat provided image

.github/workflows/gosec.yaml
Please see upstream docs here:
https://github.com/securego/gosec/
Jira: HACBS-769
=> feat(HACBS-769): use gosec in release-service ci 

controllers/suite_test.go
When running tests in verbose mode `go test -v ...` you would see a warning.
```
You're using deprecated Ginkgo functionality:
=============================================
Ginkgo 2.0 is under active development and will introduce several new features, improvements, and a small handful of breaking changes.
A release candidate for 2.0 is now available and 2.0 should GA in Fall 2021.  Please give the RC a try and send us feedback!
- To learn more, view the migration guide at https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md
- For instructions on using the Release Candidate visit https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#using-the-beta
- To comment, chime in at https://github.com/onsi/ginkgo/issues/711
You are using a custom reporter.  Support for custom …
```
=> chore(hacbs-773): Solve Ginko v2 deprecation warnings

controllers/release/release_adapter.go, tekton/pipeline_run.go, tekton/pipeline_run_test.go, tekton/predicates_test.go, tekton/utils_test.go
- adds the new label `appstudio.openshift.io/application: <application-name>`
=> feat(HACBS-970): add label appstudio.openshift.io/application: <application-name>

controllers/release/release_suite_test.go, tekton/tekton_suite_test.go, test/paths.go, test/paths_test.go
fix: auto guess the fs path for pseudo versioned modules
- adds `GetRelativeDependencyPath` function to return the fs path of
pseudo-versioned modules required by the test suites.
- adds unit tests
=> fix: auto guess the fs path for pseudo versioned modules

config/samples/kcp/dev_workspace/apiexport.yaml, config/samples/kcp/dev_workspace/appstudio_v1alpha1_applicationsnapshot.yaml, config/samples/kcp/dev_workspace/appstudio_v1alpha1_release.yaml, config/samples/kcp/dev_workspace/appstudio_v1alpha1_releaseplan.yaml, config/samples/kcp/dev_workspace/namespace.yaml, config/samples/kcp/managed_workspace/apibinding.yaml, config/samples/kcp/managed_workspace/appstudio_v1alpha1_releaseplanadmission.yaml, config/samples/kcp/managed_workspace/appstudio_v1alpha1_releasestrategy.yaml, config/samples/kcp/managed_workspace/namespace.yaml, config/samples/kcp/syncer_clusterrole.yaml, config/samples/kcp/syncer_deployment.yaml
This commit adds some resource yaml files to the config/samples/kcp
directory. These are for showing how to have the controller
reconcile a simple release in a KCP environment that includes both
a dev and managed workspace. They do not use permission claims,
but may be updated to at a later date.
=> feat: add KCP sample yamls

Makefile, config/kcp/apiexport_release.yaml, config/kcp/apiresourceschema_release.yaml, config/kcp/kustomization.yaml, hack/generate-kcp-api.sh
The script was buggy and was causing problems to our CI. In addition, it was difficult to read and was using timestamps for the name prefixes instead of something better like md5 hashes.
This commit rewrites the script and updates some file names.
=> refactor: rewrite kcp script

api/v1alpha1/release_types.go, controllers/release/release_adapter.go, controllers/release/release_adapter_test.go, controllers/release/release_controller.go
This commit adds a new type of Release status error called a
TargetDisabledError. This error is used to let the user know that the
connection with the target is unsuccessful. It does not make sense to
call this a ReleaseValidationError as is currently the case, since
there is nothing invalid about the Release itself.
=> feat(HACBS-980): refactor Release status errors

config/kcp/apiexport_release.yaml, config/samples/kcp/managed_workspace/apibinding_permissionclaims.yaml, hack/generate-kcp-api.sh
This commit adds permission claims to the KCP release APIExport for the CRDs we depend on, but do not maintain. These are pipelineruns, applicationsnapshots, environments, applications, components, and
applicationsnapshotenvironmentbindings.
=> feat(HACBS-1083): add KCP Permission Claims

controllers/release/release_adapter.go
Two of the context used in functions loading resources from the cluster were using the wrong context. As a matter of fact, this is only true given the way in which load the Application, but the function loading the Application components should be more specific and provide a way to indicate the context as the Application passed as a parameter could come from the dev workspace. This will be addressed once we introduce a `loader.go` file where we will have functions to load resources from specific contexts.
=> fix: use proper context

controllers/release/release_adapter.go
Whenever the Environment is not set in the ReleasePlanAdmission the controller should not create a Binding. This allows to have strategies without the deployment part. This commit adds a check to skip processing the Binding creation for those scenarios.
=> feat(HACBS-1097): add check to skip Binding creation

config/rbac/role.yaml, controllers/release/release_adapter.go, controllers/release/release_controller.go
The binding needs to have an owner reference so it's deleted when the Application is deleted. As we are the ones creating this bindings, there's no need to set the onwer reference when the binding is updated. If the owner reference is not present, it was removed manually and there must be a reason for that.
Tests will be added as part of HACBS-1085.
=> feat(HACBS-1085): set owner reference to the binding

gitops/gitops_suite_test.go, syncer/syncer_suite_test.go
disables port binding of metrics server for syncer and gitops tests
=> fix: disables binding of metrics server for syncer and gitops tests

test/paths.go
There was a redundant conversion of string to string.
=> chore: remove redundant conversion

.tekton/push.yaml, config/kcp/apiexport_release.yaml, config/rbac/role.yaml, controllers/release/release_controller.go, hack/generate-kcp-api.sh
This commit makes some changes to have the APIExport defined in the release-service both function properly and automatically update in infra-deployments on push.
See https://github.com/redhat-appstudio/application-service/pull/192/ for a similar PR
=> feat(HACBS-1098): modify kcp resources for infra-deployments

controllers/release/release_adapter.go
Changes `Update()` to `Patch()` in the `release_adapter` as they are still causing errors (update with pending update) in the tests.
=> chore: changes outstanding Update() to Patch() in the release_adapter

api/v1alpha1/release_types.go, controllers/release/release_adapter.go, controllers/release/release_adapter_test.go
The function getReleasePipelineRun should return nil,nil when the Release PipelineRun is not found instead of nil, err which causes the operation to be Requeued.
=> fix(HACBS-1145): releases not being properly terminated

config/kcp/kustomization.yaml, config/manager/kustomization.yaml, config/rbac/role.yaml, controllers/release/release_controller.go
This commit makes changes to enable the controller to run on the kcp version of infra-deployments. Namely, it fixes apiexport content permissions and adds to the kustomization files.
=> feat(HACBS-1098): make changes to fix controller in infra-deployments

tekton/pipeline_run.go
This PR changes the pipelinerun parameter `enterprisecontractpolicy` to `enterpriseContractPolicy` to keep the camel-case standard.
=> fix: change enterpriseContractPolicy pipeline parameter to camelcase

.github/workflows/gosec.yaml
This should make nodejs 12 warning go away.
"Node.js 12 actions are deprecated."
=> fix(hacbs-1313): use checkout v3 action in gosec workflow

api/v1alpha1/release_types.go, api/v1alpha1/release_types_test.go, config/crd/bases/appstudio.redhat.com_releases.yaml, controllers/release/release_adapter.go
This commit adds functions to the Release CRD to help set its status to reflect the deployment status of the SnapshotEnvironmentBinding.
=> feat(HACBS-1274): add deploy status helper functions to release CRD

gitops/predicates.go, gitops/predicates_test.go, gitops/utils.go, gitops/utils_test.go, go.mod, go.sum
This commit adds predicates to the gitops package that allow the controller to react to changes in SnapshotEnvironmentBindings when the status reflects the component deployment status going from unknown to true or false."
=> feat(HACBS-1274): add gitops predicate for snapshotenvironmentbindings

Dockerfile
We had to move to Docker's Go image as there was
no official Red Hat 1.18 image. Now that it exists, let's switch to it.
Also, switch to ubi-micro for runtime base image.
Signed-off-by: Martin Malina <mmalina@redhat.com>
This PR is inspired by https://github.com/redhat-appstudio/integration-service/pull/78
=> refactor(HACBS-1463): use ubi go 1.18 image as base image

api/v1alpha1/release_types.go, api/v1alpha1/release_types_test.go, controllers/release/release_adapter.go, controllers/release/release_adapter_test.go, gitops/predicates_test.go, gitops/utils.go, gitops/utils_test.go, go.mod, go.sum
This commit removes the constant that defines the
SnapshotEnvironmentBinding's ComponentDeploymentConditions from the release package and instead imports it from the application-api package.
=> chore: import binding deployment status constant

controllers/release/release_adapter.go, controllers/release/release_adapter_test.go
This fixes a bug where the controller would error out if it tried to run the EnsureSnapshotEnvironmentBindingIsTracked operation and the binding CR is missing the AllComponentsDeployed Status condition.
=> fix: don't error if binding status missing

.github/workflows/pr.yml
Based on the least privilege principle,
wildcards shouldn't be used anywhere
in RBAC definitions.
Signed-off-by: Martin Malina <mmalina@redhat.com>
=> feat(HACBS-1307): add rbac wildcard check to ci

api/v1alpha1/release_types.go
This PR fix the bug in succeeded value, currentely set to "false" and must be "true" for success completion.
Signed-off-by: Happy <hbhati@redhat.com>
=> fix(HACBS-1641): correct the succeeded value for metrics reporting

gitops/predicates_test.go, gitops/utils.go, gitops/utils_test.go
The release controller should reconcile for SnapshotEnvironmentBindings that it owns and has the AllComponentsDeployed status condition go from nonexisting to true/false, similarly to how it reconciles when the condition goes from unknown to true/false. This commit adds that functionality.
=> feat(HACBS-1645): also watch binding status going from nil to true/false

api/v1alpha1/release_types.go, api/v1alpha1/release_types_test.go, controllers/release/release_adapter.go, controllers/release/release_adapter_test.go
The release status should be updated when the AllComponentsDeployed status condition on the SnapshotEnvironmentBinding goes from False to True. This fixes that functionality.
=> fix(HACBS-1720): release not updated when binding goes false to true

api/v1alpha1/release_types.go, api/v1alpha1/release_types_test.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/appstudio.redhat.com_releases.yaml, controllers/release/release_adapter_test.go, metrics/release.go, metrics/release_test.go
This commit adds two metrics - one that measures the total number of deployments released to managed environments, and one that measures release durations from when the SnapshotEnvironmentBinding was created til the release is marked as deployed.
=> feat(HACBS-1096): add a metric that details number of deployments

config/monitoring/grafana-dashboards/release-attempts.json
The queries used to show the information weren't previse enough and we weren't getting single values as expected. Instead, values were grouped by labels.
=> fix(HACBS-1673): update Grafana dashboard to remove duplicates

.tekton/pull-request.yaml, .tekton/push.yaml
Switching to new bundle since development of old one was stopped before attempt to migrate to kcp. New bundle is removing dependency on shared secret.
=> chore: STONEBLD-777 - tekton-ci: update bundle

config/crd/kustomization.yaml
This commit removes the webhook and cainjection files from the crd kustomization file. This removes the tls cert errors that currently pollute the manager pod log. The webhooks still work properly with this change.
=> feat(HACBS-1764): cleanup tls errors from webhook in manager pod

config/manager/kustomization.yaml, config/manager/network_policy.yaml
This commit adds an Egress Network Policy
to block all outgoing(Egress) traffic from release service
pod(controller-manager)
The `spec.podSelector` contains the name of a pod 
on which we want to apply network policy
`spec.egress` have Whitelist rules to allow the necessary
traffic to certain pods and namespaces.
This change is tested on the hyper-shift child cluster(OVN) and
QuickLab SDN and OVN clusters.
Child Hypershift cluster requires adding an endpoint in  
`ipBlock:` `cidr`. 
To get `CIDR` perform `oc get ep -n default` and add
Kubernetes endpoints in `ipBlock`.  This will allow the pod to talk with
k8s API. 
***Reach out to the PR owner if you want to test on the Hypershift cluster.***
* For testing this change you need to have an Openshift cluster
* Clone your fork of …
=> feat(HACBS-1308): add an egress network policy

go.mod, main.go
This is a requirement set in the logging conventions seen in ADR/0006.
=> feat(HACBS-2017): use ISO8601 for timestamps

.github/workflows/codecov.yml
Update go version to 1.18 and codecov-actions to v3
=> fix(hacbs-1680): bump up go and codecov versions

api/v1alpha1/release_webhook.go, api/v1alpha1/release_webhook_test.go, api/v1alpha1/webhook_suite_test.go, config/webhook/manifests.yaml, gitops/gitops_suite_test.go, go.mod, main.go, syncer/syncer_suite_test.go, tekton/tekton_suite_test.go
This commit modifies the Release webhook to be a low level one. The main reason for this is so that whenever a Release CR is created or modified, a label is set which depicts the username of who created or modified the CR. This value will end up being used in release pipelines.
=> feat(HACBS-2125): capture user who creates Release

api/v1alpha1/release_types.go, api/v1alpha1/release_webhook.go, api/v1alpha1/release_webhook_test.go, api/v1alpha1/releaseplan_webhook.go, api/v1alpha1/releaseplan_webhook_test.go, api/v1alpha1/releaseplanadmission_webhook.go, api/v1alpha1/releaseplanadmission_webhook_test.go, controllers/release/adapter_test.go, loader/loader.go, loader/loader_test.go, metadata/labels.go, metadata/metadata_test.go, tekton/pipeline_run.go, tekton/utils.go
Looking around some `k8s` projects I noticed they use `labels.go` to keep their labels in. Not sure about the proper place and if should we move any other label here so far.
- moves release related labels to `labels.go` at `api/v1alpha1`
=> chore(hacbs_1032): move ReleasePlan and ReleasePlanAdmission label to a proper place

controllers/release/adapter.go, controllers/release/adapter_test.go, tekton/pipeline_run.go, tekton/pipeline_run_test.go
This change adds a new function to declare new Pipeline parameters. This function allows to pass any number of client.Objects. The kind of the object will be used as the parameter name while the value will contain the namespaced name of the object.
In addition, every new ReleasePipelineRun will contain a reference to the Release.
=> feat(HACBS-2129): add release reference as a Pipeline parameter

metadata/labels.go
I need to use this in my work in the integration-service, so I am adding it before the [hacbs-2127](https://issues.redhat.com//browse/hacbs-2127) work for release-service
=> feat(HACBS-2127): add automated label to metadata

api/v1alpha1/release_types.go, api/v1alpha1/release_types_test.go, config/crd/bases/appstudio.redhat.com_releases.yaml
@davidmogar not sure if you want me to create a `r.markAutomated` function that sets the status or just set the status directly in integration-service. Figured you'd have an opinion on it so only added the field until I hear it
=> feat(HACBS-2127): add automated to release status

.tekton/push.yaml
We need the latest Release code to be merged before the dashboard is added to infra. This rewrite (or even the previous one) is preventing that to happen as the path doesn't exist yet.
=> fix: remove rewrite

.github/workflows/pr.yml, Dockerfile, go.mod
Bumping go version to 1.19 as integration-service is about to bump version to 1.19 and new dependencies may not be buildable with 1.18 if you bump version of integration-service in future
=> chore(HACBS-2270): use go 1.19

controllers/release/adapter.go, controllers/release/adapter_test.go
A reference to the ReleasePlanAdmission CR is now passed as a parameter to the release PipelineRun.
This will allow us to access the extraData field in the RPA.
=> feat(HACBS-2224): add reference to ReleasePlanAdmission to release pr

Makefile
Updates the kubebuilder-tools in the Makefile from 1.23 to 1.27.1
=> feat(HACBS-2279): update kubebuilder-tools to 1.27.1

config/manager/manager.yaml
The label cannot be defined here as per the documentation [1].
[1] https://github.com/redhat-appstudio/infra-deployments/tree/main/components/monitoring
=> fix: remove monitoring label

.github/workflows/dependabot.yml
Adds a new github actions workflow, dependabot.yml, to automatically check for specified dependency updates and opens a PR when an update is detected.
=> feat(HACBS-2273): use dependabot to update actions

.github/workflows/codecov.yml, .github/workflows/pr.yml
Dependabot opened PRs for bumping the versions of some actions. The dependabot PRs don't meet our gitlint standards, so until we have a solution for that, we should probably manually bump the versions it recommends. This takes care of that for the github actions.
=> chore(actions): bump versions

.tekton/push.yaml, config/grafana/dashboard.yaml, config/grafana/dashboards/release_dashboard.json
as part of this bug fix and the upgrade to `GrafanaOperator` v5, we have to update the `GrafanaDashboard` resource to match the new api
More details:
https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1690371680784569
The dashboard is still presenting data due to a patch we merged to RHTAP, and it will be removed after these changes will be merged
=> fix: Update GrafanaDashboard to match GrafanaOperator v5 (RHTAPWATCH-8)

.github/workflows/gosec.yaml
This will add a step to upload sarif file generated by gosec to Github using the upload-sarif action.
That way if gosec finds issues in the code,
Github UI will show them inline in the Files
tab of a PR.
=> feat(HACBS-1725): improve gosec pr check

config/manager/network_policy.yaml
This commit will add a additional kubernates CIDR
to allow traffic to as per the requirement from ROSA cluster.
=> feat(HACBS-2427): update network policy to add additional port to CIDR

controllers/release/adapter.go, tekton/pipeline_run.go, tekton/pipeline_run_test.go
When release pipelineruns are created, they will always use the same shared workspace (provided by the default PVC, or one defined in the given ReleaseStrategy). This wasn't an issue before, but now that we started using the workspace to share snapshot and other data from task to task, we found one that two simultaneously running pipelineruns can alter each other's data. We need to prevent that.
This typically happens when you have two or more components in your app and so there are multiple pipeline runs, oftentimes running around the same time.
The solution is to use a subdir when passing the PVC in the PR. The subdir is based on the PR's UID, so it should always be unique.
Here's the accompanying PR to enable the failing test in e2e tests: …
=> fix(RHTAPBUGS-560): ensure each pipelinerun uses its own subdir

controllers/release/adapter.go, tekton/pipeline_run.go, tekton/pipeline_run_test.go
Recently we made a change to start using subPath
when defining a workspace during PipelineRun creation.
This was to fix an issue when 2 or more PRs running in parallel would override each other's data.
It turns out that there is a race condition happening often when kubernetes tries to create the subPath in the volume. When there are several pods with the same subPath created at the same time (as is the case with Tekton PRs - there are pods for each task), it can happen that several pods try to create the subPath and only one of them succeeds. See jira for more details.
We'll have to find another solution to the problem we were fixing with this. In the meantime, we'll have to revert this.
This reverts commit 25cfcdb12688b0b679cd4beb923662e580ef2da3.
=> fix(RHTAPBUGS-691): revert subPath creation in PRs

.github/gitlint/contrib_format_conventional_commits.py
Updates gitlint to support "revert" as a prefix
=> feat(HACBS-2506): add revert prefix support

config/rbac/release_editor_role.yaml, config/rbac/release_viewer_role.yaml, config/rbac/releaseplan_editor_role.yaml, config/rbac/releaseplan_viewer_role.yaml, config/rbac/releaseplanadmission_editor_role.yaml, config/rbac/releaseplanadmission_viewer_role.yaml, config/rbac/releasestrategy_editor_role.yaml, config/rbac/releasestrategy_viewer_role.yaml
This change should cause these roles to be aggregated into the system wide view, edit, and admin clusterroles.
Notably, it will also cause the roles to be aggregated into the dedicated-admin role, which is what I'm really after.
=> fix(RHTAPBUGS-714): aggregate clusterroles

config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml
This is addressing an issue reported by kube-linter, see [1] for rule description.
[1]https://github.com/stackrox/kube-linter/blob/main/docs/generated/checks.md#no-read-only-root-fs
=> fix(HACBS-2481): set readOnlyRootFilesystem for controller-manager

controllers/release/adapter.go, controllers/release/adapter_test.go, go.mod, go.sum
The Operator Toolkit validator allow us to define the validation functions and helps on testing the EnsureReleaseIsValid operation as now those validation functions can be mocked.
=> feat: make use of the toolkit validator

.gitlint
This came up when reviewing this PR from dependabot: https://github.com/redhat-appstudio/release-service/pull/249
Oftentimes it's hard to fit within 72 chars for the commit message body, typically when there is a long url. This should help.
Limit for commit title will stay at 72 chars.
=> chore: increase commit message line length limit

controllers/release/adapter_test.go, tekton/pipeline_run.go, tekton/pipeline_run_test.go
The EnterpriseContact ConfigMap now contains the information needed for the git resolver of the proper task to use. This commit changes the adapter from passing the task bundle information to passing the task git resolver information.
=> refactor(HACBS-2550): pass git resolver info for verify-ec task

config/grafana/dashboards/release_dashboard.json
The Release Grafana dashboard was not working properly. I found out that some filters were not properly defined. I also saw that one of the panels was deprecated, so I updated it.
In any case, there seems to be an unrelated problem. Just editing the panels and clicking on the query was enough for the panel to start showing values (without any changes). Let's see how it behaves after this change.
=> fix: update filters and panels

.github/workflows/codecov.yml
We have an error as atomic.Pointer is requested by a dependency and go 1.18 doesn't supply an implementation for it.
=> fix: bump go version

Dockerfile
- change required to adhere to @redhat enterprise contract policy
- certain labels need to be defined at container level and cannot be inherited.
```
The "description" label should not be inherited from the parent image
The "io.k8s.description" label should not be inherited from the parent image 
The "io.k8s.display-name" label should not be inherited from the parent image 
The "summary" label should not be inherited from the parent image
```
=> chore(RHTAPREL-435): update dockerfile

loader/loader_mock.go
No need to add type and iota to each enum member.
=> refactor: simplify enum declaration

controllers/release/adapter_test.go, tekton/pipeline_run.go, tekton/pipeline_run_test.go
This commit reverts
https://github.com/redhat-appstudio/release-service/pull/248 and has the operator pass a bundle ref for the verify-enterprise-contract task in the release pipelines once again.
=> revert(RHTAPREL-654): revert to using bundle resolver for ec

config/crd/bases/appstudio.redhat.com_releaseplanadmissions.yaml, config/crd/bases/appstudio.redhat.com_releaseplans.yaml, controllers/release/adapter.go, controllers/release/adapter_test.go, tekton/pipeline_run.go, tekton/pipeline_run_test.go, tekton/utils/pipeline_ref.go
This commit adds a field named timeout to the PipelineRef struct. If it is provided in a ReleasePlanAdmission, it is passed to the release PipelienRun to override the default timeout value.
=> fix(RHTAPBUGS-964): override pipelinerun timeout via RPA

api/v1alpha1/release_types.go, api/v1alpha1/releaseplan_types.go, api/v1alpha1/releaseplanadmission_types.go, api/v1alpha1/releaseserviceconfig_types.go, config/crd/bases/appstudio.redhat.com_releaseplanadmissions.yaml, config/crd/bases/appstudio.redhat.com_releaseplans.yaml, config/crd/bases/appstudio.redhat.com_releases.yaml, config/crd/bases/appstudio.redhat.com_releaseserviceconfigs.yaml
Add the rp shortname for ReleasePlan and rpa shortname for ReleasePlanAdmission.
```
$ oc get rp
NAME   APPLICATION   TARGET
rp     foo           rpas
$ oc get rpa
NAME   ENVIRONMENT   ORIGIN
rpa    production    rpas
```
=> feat(RHTAPREL-711): add shortnames to CRDs

controllers/release/adapter_test.go, metadata/labels.go, tekton/pipeline_run.go, tekton/pipeline_run_test.go
Exposes release pipeline run snapshot information as a label
=> fix(RHTAPBUGS-859): exposes snapshot reference to the UI

controllers/release/controller.go, go.mod, go.sum
This commit changes the Release controller to ignore Releases that come from a backup restore.
=> feat(RHTAPREL-763): ignore Releases restored from backup

loader/loader.go, loader/loader_test.go, metadata/labels.go
This commit changes the logic for fetching a ReleasePlanAdmission for a given ReleasePlan. If the ReleasePlan contains a label for the ReleasePlanAdmission to use, that ReleasePlanAdmission is searched for directly. This allows operations to continue even if multiple ReleasePlanAdmissions exist in a single managed namespace.
=> feat(RHTAPREL-764): allow RPs to specify RPAs

Makefile, api/v1alpha1/release_types.go, api/v1alpha1/releaseplan_types.go, api/v1alpha1/releaseplanadmission_types.go, config/crd/bases/appstudio.redhat.com_releaseplanadmissions.yaml, config/crd/bases/appstudio.redhat.com_releaseplans.yaml, config/crd/bases/appstudio.redhat.com_releases.yaml, controllers/release/adapter.go, controllers/release/adapter_test.go, loader/loader.go, loader/loader_mock.go, loader/loader_mock_test.go, loader/loader_test.go, metadata/labels.go, tekton/pipeline_run.go, tekton/predicates.go, tekton/predicates_test.go, tekton/utils.go
Rename references to the release Pipeline{Run} to managed Pipeline{Run}.
=> refactor(RHTAPREL-715): rename PipelineRun references

controllers/release/adapter.go, controllers/release/adapter_test.go, tekton/pipeline_run.go, tekton/pipeline_run_test.go
If a git resolver is used in the RPA, pass the revision value from it to the release pipelineRun as the taskGitRevision parameter.
=> feat(RHTAPREL-790): pass taskGitRevision param to plr

controllers/release/adapter.go, controllers/release/adapter_test.go, tekton/pipeline_run.go, tekton/pipeline_run_test.go
If a git resolver is used in the RPA, pass the url value from it to the release pipelineRun as the taskGitUrl parameter.
=> feat(RHTAPREL-792): pass taskGitUrl param to plr

README.md, api/v1alpha1/release_types.go, metrics/release.go, metrics/release_test.go
This PR adds the missing metrics for the release-service to implement the alert/visualisations for the agreed SLO
=> chore(RHTAPREL-304): add missing metrics for SLO alerts

.github/CODEOWNERS
A new GitHub group named `konflux-release-team` was created to replace `Release Team`. Use new one to be able to delete former one.
The context of this new group name is to align with new service name but also with the name of existing Rover group. Having both GitHub and Rover group names aligned will allow to have clusters auth with either GitHub or Red Hat SSO without having any difference in the RBACs.
[RHTAPSRE-287](https://issues.redhat.com//browse/RHTAPSRE-287)
=> feat(RHTAPSRE-287): use new group name in codeowners

controllers/releaseplan/controller.go
This commit reorders the operations in the ReleasePlan controller so that the application owner reference is set last. If the application is not found, the reconcile loop errors. This means that if the application is not yet created, the other operations will not run, and (at this time) no matching information will be set. With this commit, the matching information is set before, as this does not rely on the application CR existing.
=> fix(RHTAPREL-810): reorder operations in ReleasePlan controller

api/v1alpha1/webhooks/release/suite_test.go, api/v1alpha1/webhooks/release/webhook.go, api/v1alpha1/webhooks/release/webhook_test.go
With this change, the loader is used in the webhook, which allow us to use the MockLoader to avoid the flakiness of calling the actual client.
=> fix: use loader to avoid using the client

.github/workflows/gosec.yaml
A while ago we modified the workflow to save the results in a SARIF file and then upload to Github to show issues in the UI, but somehow it does not seem to work right now and there is no way to see what's wrong.
This change adds a second run of gosec which will
print the issues in the log directly.
This is related to https://github.com/redhat-appstudio/release-service/pull/363 where we were repeatedly getting failures for gosec, but we couldn't see what the issue was - we just saw that it failed, but there was nothing in the UI. With this change, we can now see the error:
```
Golang errors in file: []:
> [line 0 : column 0] - error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```
Likely because the error is weird and not related to a specific file, …
=> fix: modify gosec PR check to log results

config/manifests/kustomization.yaml, config/manifests/release_service_config.yaml
This commit adds a default ReleaseServiceConfig to the manifests directory so one is created when the operator is deployed.
=> feat: add default ReleaseServiceConfig

Dockerfile
We need to add the `name` and `com.redhat.component` labels to avoid an EC violation.
=> chore: add `name` and `com.redhat.component` labels

controllers/release/adapter.go, controllers/release/adapter_test.go
Our manager logs were being cluttered with automated validations errors as those were requeued forever. Now, if the error appears after 5 minutes of the release being created (time enough for the Integration service to set the Release as automated) the error is reported and the Release marked as failed.
=> feat(RHTAPREL-783): do not requeue automated errors

api/v1alpha1/releaseplan_types.go, config/crd/bases/appstudio.redhat.com_releaseplans.yaml
The release-service deployment is CrashLooping right now. It is possible that this is caused by multiple RP/RPAs being reconciled because an error that arises whenever the name of a matched RPA is set to empty string. This is a quick fix to remove the pattern check and see if this improves the situation.
=> fix: remove pattern

controllers/release/adapter.go, controllers/release/adapter_test.go, controllers/release/controller.go
The Release Processing resources were cleaned up as part of the operation that tracks the Processing status and if an error occurred cleaning them up, it was not retried. This commit breaks the cleanup out into its own operation that will run once the Release is marked as Processed and properly retries if an error occurs during cleanup.
=> fix(RHTAPREL-854): add processing cleanup operation to Release adapter

Makefile, config/manager/kustomization.yaml
This commit changes the references to redhat-appstudio/release-service to konflux-ci/release-service as the location for pushing this operator was migrated.
=> refactor(RELEASE-977): migrate to konflux-ci quay org

config/crd/bases/appstudio.redhat.com_releaseplanadmissions.yaml, config/crd/bases/appstudio.redhat.com_releaseplans.yaml, controllers/release/adapter.go, controllers/release/adapter_test.go, controllers/releaseplan/adapter_test.go, tekton/utils/pipeline.go
This commit updates the 'Pipeline' struct by renaming the 'ServiceAccount' field to 'ServiceAccountName'.
Jira: [Link](https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=19560&projectKey=RELEASE&view=planning&selectedIssue=[RELEASE-523](https://issues.redhat.com//browse/RELEASE-523)&quickFilter=124517&issueLimit=100#)
Changes:
* Renamed 'ServiceAccount' field to 'ServiceAccountName' in the Pipeline struct.
=> Chore(RELEASE-523): Rename ServiceAccount field to ServiceAccountName

api/v1alpha1/webhooks/author/webhook.go, api/v1alpha1/webhooks/author/webhook_test.go
K8s allows usernames to be in the format of an email address. Changing the the author mutating webhook to support it.
closes https://github.com/konflux-ci/release-service/issues/529
=> Support email usernames

.gitlint
This commit modifies the gitlint configuration to ignore the max title length and max body line length rules for bot accounts. This should encompass both dependabot commits and red-hat-konflux-bot commits.
=> fix: ignore gitlint checks for bots

cache/cache.go, controllers/release/controller.go, loader/loader.go, loader/loader_mock.go, loader/loader_mock_test.go, loader/loader_test.go, loader/suite_test.go
A new funciton has been added to the loader to be able to get the Release created just before a given Release. This is a key function for the collectors feature.
=> feat(RELEASE-913): add GetPreviousRelease loader function

controllers/release/adapter.go, controllers/release/adapter_test.go
The deployment related code was removed a while ago. Remove remaining syncResources function.
=> chore: remove lingering deployment code

api/v1alpha1/release_conditions.go, api/v1alpha1/release_types_test.go
The deployed condition was dropped a while ago, but the condition was still lingering in some tests.
=> chore: remove lingering deployment condition

api/v1alpha1/collectors.go, config/crd/bases/appstudio.redhat.com_releaseplanadmissions.yaml, config/crd/bases/appstudio.redhat.com_releaseplans.yaml
[RELEASE-910](https://issues.redhat.com//browse/RELEASE-910) talks about passing a timeout with the collector, but no timeout field was included when they were added with RELEASE-908. This commit adds the timeout field.
=> feat(RELEASE-910): add timeout field to collectors

api/v1alpha1/releaseserviceconfig_types.go, config/crd/bases/appstudio.redhat.com_releaseserviceconfigs.yaml
Remove AdvisoryRepo from ReleaseServiceConfig Spec as it is no longer used.
=> chore(RELEASE-903): remove advisoryRepo from RSC

loader/loader.go, loader/loader_test.go
This commit fixes the issue of FieldSelectors retrurning everything when the argument is nill, added checks to each function using field selector.
=> fix(RELEASE-1150) add checks to fieldselectors

.github/workflows/pr.yml
Latest ubuntu does not allow system wide pip install. It can be overriden with `--break-system-packages`, but it's better to create a virtual env.
This first came up here: https://github.com/hacbs-release/app-interface-deployments/pull/198
=> fix: gitlint installation

loader/loader.go, loader/loader_test.go
This commit fixes the loader function to return nil instead of an empty RPA if the RPA specified in the RP label does not exist.
=> fix(KFLUXBUGS-1754): rp shouldn't show matched if RPA doesn't exist

controllers/release/adapter.go, controllers/release/adapter_test.go
This commit adds a new validation function to ensure that the Application referenced in the ReleasePlan and in the Snapshot is the same.
=> feat(RELEASE-1124): validate Application reference

api/v1alpha1/release_types.go, metrics/release.go
this commit fixes the order which the metrics
parameters are sent, causing wrong data being
sent
=> fix: metrics fields in wrong order

metrics/release.go, metrics/release_test.go
this PR fixes the order of metrics labels and values, and in addition modifies tests to use arbitrary strings intead of values from the label array, which was causing the test to not identify when the value was misplaced.
=> fix: metrics still in wrong order

controllers/release/adapter.go, controllers/release/adapter_test.go
If a ReleasePlanAdmission is found with auto-release set to false, it will continually requeue the error because it is not a not found error. Instead, the Release should be marked as validation false and reconciliation should end.
=> fix(KFLUXBUGS-1921): auto-release false RPA should end reconcile

.tekton/release-service-pull-request.yaml, .tekton/release-service-push.yaml
One of the images used in the build pipeline was deleted, so this commit switches us to a different sha of the task.
=> fix: build pipeline task sha was removed

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
Update integration-test pipeline to enable test-results-analyzer
https://issues.redhat.com/browse/KFLUXDP-109
=> feat(KFLUXDP-109): enable test-results-analyzer

controllers/releaseplan/adapter_test.go
envtest doesn't delete owned resources, so the test checking that the releasePlan was removed when the application was deleted in the releasePlan adapter was misleading. It only was passing because it was missing the namespace. This commit removes the misleading test and improves the one checking the ownerReference.
=> test: fix owner reference test in releasePlan adapter

controllers/release/adapter.go, controllers/release/adapter_test.go, controllers/release/controller.go, metadata/labels.go
This commit adds an operation to the release controller to set metadata from the application on the release. It sets the ownerReference to be the application as well as copies the pipelines as code and rhtapDomain labels and annotations from the snapshot to the release. This is currently done for automated releases by the integration service, so this commit moves the logic to the release controller instead.
=> feat(RELEASE-1227): set application metadata in release controller

config/default/manager_auth_proxy_patch.yaml, controllers/release/adapter.go, main.go, metadata/labels.go
this PR tries to fix/decrease the daily crashes of the release controller by filtering objects to cache and increasing the lease renew time.
=> fix(RELEASE-1277): release controller crashes

config/manager/kustomization.yaml, config/manager/release_service_config.yaml
- the rsc needs to managed outside of the release service so that clusters can have a specific version for testing.
- A version can be deployed and managed by ArgoCD via infra-deployments for a specific cluster
=> fix(RELEASE-1441): remove rsc from being managed

.github/workflows/codecov.yml, .github/workflows/gosec.yaml, .github/workflows/pr.yml
Migrate GitHub workflows from Ubuntu 20.04 Ubuntu-latest
=> chore(RELEASE-1444): upgrade GitHub workflows to Ubuntu-latest

controllers/release/adapter.go, controllers/release/adapter_test.go
The collectors PRs were missing the service label so they were never cached. This made reconciliations to fail.
=> fix: add service label

.dockerignore, .tekton/release-service-pull-request.yaml, .tekton/release-service-push.yaml, Dockerfile, config/manager/network_policy.yaml, integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
Added Sealights instrumentation task to the build process to enable tracking
and monitoring of test coverage during builds. Adjusted build pipelines to
create a new container image that includes the Sealights agent, making it
ready for instrumentation. Enabled e2e tests to sync with Sealights by
sending test reports for coverage tracking.Future improvements will include
test selection, optimizing test run times, and reducing cloud costs
=> feat(RELEASE-1452): onboard sealights to release service

config/default/manager_metrics_patch.yaml, config/default/metrics_service.yaml, config/prometheus/monitor.yaml
this PR changes the metrics port to 8080 as the service
in this port is not secured in the pod side
=> fix: change port to 8080 and endpoint to insecure

api/v1alpha1/collectors.go, controllers/release/adapter.go, tekton/utils/pipeline.go, tekton/utils/pipeline_test.go
- The git resolver url value passed from the controller to the
run-collectors pipeline should be inherited from the RPA.
- introduce constants for default catalog url, revision and
pathInRepo values for collectors.
=> fix(RELEASE-1473): use rpa url for git resolver

.tekton/release-service-push.yaml
- use latest trusted sha for the buildah-oci-ta task
=> fix: update task ref for build-sealights-container

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
Check docs for more info: https://konflux.pages.redhat.com/docs/users/testing/integration/choosing-contexts.html
=> feat: remove Release e2e pipelines events in favor of integration service contexts

controllers/release/adapter.go, controllers/release/adapter_test.go
This commit fixes the validateApplication function in the release adapter to mark the release as invalid if the Application in the Snapshot and ReleasePlan do not match. Previously, it would be endlessly requeued with error.
=> fix(RELEASE-1503): end reconcilation if application doesn't match

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
* use [kind cluster](https://github.com/konflux-ci/tekton-integration-catalog/tree/main/tasks/mapt-oci/kind-aws-spot) as a testing infra
* [deploy using konflux-ci scripts](https://github.com/konflux-ci/tekton-integration-catalog/tree/main/tasks/konflux-ci/deploy/0.1) instead of infra-deployments
* [skip bootstrapping a cluster in e2e-tests repo](https://github.com/konflux-ci/e2e-tests/pull/1606)
https://issues.redhat.com/browse/KFLUXDP-290
=> feat: use aws kind cluster for testing

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
Currently, in Tekton, finally tasks that are dependent on the results of a preceding task will not be scheduled if that preceding task is cancelled or fails before generating the expected result. Basically changing the result to a generated param..
=> fix: use predefined name for kind kubeconfig secret and bump to 0.2

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
We dont need anymore to push artifacts to quality dashboard. The dashboard is able to pull the artifacts automatically after implementing https://issues.redhat.com/browse/KFLUXDP-240
=> feat(KFLUXDP-239): remove quality dashboard task

.tekton/release-service-push.yaml
The image tags are currently in the "on-pr-<commit-sha>" format for
both push and pull request events.
This PR changes the tag format for push events to distinguish them
from those for pull request events.
=> fix: release service image tag in push events

api/v1alpha1/releaseplan_types.go, api/v1alpha1/releaseplan_types_test.go, api/v1alpha1/releaseplanadmission_types_test.go, api/v1alpha1/webhooks/releaseplanadmission/webhook.go, api/v1alpha1/webhooks/releaseplanadmission/webhook_test.go, controllers/release/adapter_test.go, controllers/utils/predicates/predicates.go, controllers/utils/predicates/predicates_test.go, loader/loader.go, loader/loader_test.go, metadata/labels.go
This commit is the first for [RELEASE-1352](https://issues.redhat.com//browse/RELEASE-1352). It adds the block-releases label for ReleasePlanAdmissions. This will take the place of the auto-release label, with the hope of increasing clarity. The auto-release label still exists with this commit, but once all ReleasePlanAdmissions are migrated, a future commit will remove it (just for RPAs, not for RPs).
=> refactor(RELEASE-1352): add block-releases label to RPAs

api/v1alpha1/releaseplan_types.go, api/v1alpha1/releaseplan_types_test.go, api/v1alpha1/releaseplanadmission_types_test.go, api/v1alpha1/webhooks/releaseplanadmission/webhook.go, api/v1alpha1/webhooks/releaseplanadmission/webhook_test.go, controllers/release/adapter_test.go, controllers/utils/predicates/predicates_test.go, loader/loader.go, loader/loader_test.go
A previous commit (PR 791) made changes for the block-releases label to take the place of the auto-release label on ReleasePlanAdmissions. This enabled us to migrate existing ReleasePlanAdmissions to use the new label. Now that it has been done, this commit cleans up the auto-release label (and logic) on ReleasePlanAdmissions.
=> chore(RELEASE-1352): cleanup old RPA auto-release code

.github/workflows/pr.yml
A dependabot PR was created for this but it had no signature. I created this one to be merged.
=> chore: bump static_check version

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
Sometimes we're hitting this error during kind cluster provisioning
```
Your Spot request price of 0.26771999999999996 is lower than the minimum required Spot request fulfillment price of 0.3724
```
For a better chance to get a cheap spot instance we need to increase the value of `spot-increase-rate` param (default is 20)
Otherwise this PR fixes the name of the file which contains the log from the aws kind provisioning task (see e.g. [here](https://app-artifact-browser.apps.rosa.konflux-qe.zmr9.p3.openshiftapps.com/release-service/konflux-e2e-tests-v84sd/)). it's used by test results analyzer
=> fix: increase spot instance price

api/v1alpha1/release_types.go, controllers/release/adapter.go, controllers/release/adapter_test.go, loader/loader.go, loader/loader_mock.go, loader/loader_test.go, metadata/labels.go, metadata/metadata_test.go, tekton/predicates_test.go, tekton/utils.go, tekton/utils_test.go
Instead of having a bunch of strings for the pipelineType and comparing against it, we should use an enum for it. This comes from [#549](https://github.com/konflux-ci/release-service/pull/549#discussion_r1764942351)
It would be cleaner and less error prone.
##Relevant Jira
[RELEASE-1180](https://issues.redhat.com/browse/RELEASE-1180)
Signed-off-by: elenagerman [elgerman@redhat.com](mailto:elgerman@redhat.com)
=> refactor(RELEASE-1180): use enum for pipelineType in release controller
